---
title: "Data Science Capstone - Final Project Submission."
author: "Meltem YILMAZ"
date: "4/20/2021"
subtitle: "Use LEFT/RIGHT to navigate slide"
output: 
  revealjs::revealjs_presentation:
    incremental: false
    theme: moon
    highlight: haddock
    center: true
    self_contained: false
    reveal_options:
      slideNumber: true
      previewLinks: true
---

```{r setup, include=FALSE}
library('lubridate')
library('revealjs')
```

# Assignment: Final Project Submission

**Instructions**

  The goal of this exercise is to create a product to highlight the prediction algorithm that you have built and to provide an interface that can be accessed by others. For this project you must submit:

  - A Shiny app that takes as input a phrase (multiple words) in a text box input and outputs a prediction of the next word.
  - A slide deck consisting of no more than 5 slides created with [R Studio Presenter](https://support.rstudio.com/hc/en-us/articles/200486468-Authoring-R-Presentations) pitching your algorithm and app as if you were presenting to your boss or an investor.

# Review criteria

**Data Product**

  - Does the link lead to a Shiny app with a text input box that is running on shinyapps.io?
  - Does the app load to the point where it can accept input?
  - When you type a phrase in the input box do you get a prediction of a single word after pressing submit and/or a suitable delay for the model to compute the answer?
  - Put five phrases drawn from Twitter or news articles in English leaving out the last word. Did it give a prediction for every one?

# Text-Mining

  In the shiny app, users can casually key in any character inside text box. The the system will auto appear the suggested next predictive words in table format by follow the most accurate in sequence. You can show/hide the author and source code link if you like.

# Short Brief

  I am using `tm` and `RWeka` packages for previous assignments, but occassionaly noticed a new package `quanteda` which is more efficient and clean, clear and concise and text mining and n-grams words prediction. At the same time I am using [`shinyjs`](https://github.com/daattali/shinyjs) package to come out with better output and interactive. 

  You are feel free to browse over the shiny app at [Final Project-Submission (Shiny App)](https://nobatgeldi.shinyapps.io/Natural-Language-Analysis/).

# Appendices

**System :**

  - R version (short form): `r getRversion()`
  - Author Profile: [Nobatgeldi Geldimammedov](https://github.com/meltemyilmaz024)
  - GitHub: [Source Code](https://github.com/meltemyilmaz024/Natural-Language-Analysis)
  
**References :**

  - [**Capstone Project IOSlides** *by Ryo, Eng Lian Hu March 14, 2015*](http://rpubs.com/englianhu/Capstone_Project_IOSlides)
  - [quanteda: Quantitative Analysis of Textual Data](http://kbenoit.github.io/quanteda/intro/overview.html)
  - [**Coursera Capstone Project Milestone Report** *by Ryo, Eng Lian Hu 2016-04-26*](http://rpubs.com/englianhu/Milestone-Report)
  - [**Final_W2** *by Hsing-Yi 2016年4月24日*](http://rpubs.com/Hsing-Yi/176027)